// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbyetislkivlyjrjfipd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhieWV0aXNsa2l2bHlqcmpmaXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTc1MzIsImV4cCI6MjA1OTc5MzUzMn0.8gFywD6zFwUlTFiyvWrIzfFD9FbfN1xvPBOnPqEmmow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);