
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akesgjriqwoywecwuser.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZXNnanJpcXdveXdlY3d1c2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDAxODcsImV4cCI6MjA2MDUxNjE4N30.kTitOcvge71qGf09J2lp8spEGdoXsfkRWQnhJ5wlqAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom type definitions to be used throughout the application
export type Tables = {
  classes: {
    id: string;
    date: string;
    start_time: string;
    end_time: string;
    max_capacity: number;
    program_id: string;
    coach_id: string;
    created_at?: string;
    updated_at?: string;
    programs?: {
      id: string;
      name: string;
      description?: string;
    };
    profiles?: {
      id: string;
      name: string;
      avatar_url?: string;
    };
    checkins?: Array<{
      id: string;
      user_id: string;
      status: string;
      checked_in_at?: string;
      profiles?: {
        id: string;
        name: string;
        avatar_url?: string;
      };
    }>;
  };

  profiles: {
    id: string;
    name: string;
    email: string;
    avatar_url?: string;
    role: string;
    status: string;
    phone?: string;
    birth_date?: string;
    created_at?: string;
  };

  programs: {
    id: string;
    name: string;
    description?: string;
    created_at?: string;
    updated_at?: string;
  };

  checkins: {
    id: string;
    class_id: string;
    user_id: string;
    status: string;
    checked_in_at?: string;
    profiles?: {
      id: string;
      name: string;
      avatar_url?: string;
    };
    classes?: {
      id: string;
      date: string;
      start_time: string;
      end_time: string;
      program_id: string;
    };
  };
};
